# Generated by Django 5.1.2 on 2024-10-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Цветы')),
                ('company', models.CharField(max_length=100, verbose_name='ZAMI_flowers')),
                ('price', models.CharField(default='без опыта', max_length=80, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Лаванда')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZAMI_app.category', verbose_name='Выберите категории')),
            ],
            options={
                'verbose_name': 'Цветы',
                'verbose_name_plural': 'Цветы',
            },
        ),
    ]
