# Generated by Django 5.1.2 on 2024-10-26 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZAMI_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='created_ad',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
