# Generated by Django 5.1.2 on 2024-10-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZAMI_app', '0003_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='crated_at',
            new_name='crеated_at',
        ),
    ]
