# Generated by Django 5.1.2 on 2024-10-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZAMI_app', '0004_rename_crated_at_guide_crеated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowers_images/', verbose_name='Изображение'),
        ),
    ]
