# Generated by Django 5.1.2 on 2024-10-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZAMI_app', '0005_flowers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='image',
            field=models.CharField(max_length=500, verbose_name='URL-фото'),
        ),
    ]
